name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install RIVEMU
      - name: Install RIVEMU
        run: |
          wget -O rivemu https://github.com/rives-io/riv/releases/latest/download/rivemu-linux-amd64
          chmod +x rivemu
          mkdir -p $HOME/.riv
          mv rivemu $HOME/.riv/
          echo "$HOME/.riv" >> $GITHUB_PATH

      # Install RIV SDK
      - name: Install RIV SDK
        run: |
          wget -O rivos-sdk.ext2 https://github.com/rives-io/riv/releases/latest/download/rivos-sdk.ext2
          mkdir -p $HOME/.riv
          mv rivos-sdk.ext2 $HOME/.riv/
          echo "RIVEMU_SDK=$HOME/.riv/rivos-sdk.ext2" >> $GITHUB_ENV

      # Verify installations
      - name: Verify RIVEMU and SDK installation
        run: |
          rivemu -version
          rivemu -quiet -no-window -sdk -exec gcc --version

      # Build the project
      - name: Build the project
        run: make build

      # Upload to GitHub Releases
      - name: Upload Artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: wordslide.sqfs
